# Generated by Django 4.2.5 on 2023-10-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votacao", "0002_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="max_votos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aluno",
            name="numero_grupo",
            field=models.IntegerField(default=0),
        ),
    ]
