# Generated by Django 4.2.6 on 2023-10-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subreddit", "0003_vote_comment_alter_vote_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
