# Generated by Django 4.2.6 on 2023-10-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subreddit", "0005_rename_votes_post_total_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="subreddit.post",
            ),
        ),
    ]
