# Generated by Django 4.2.6 on 2023-10-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subreddit", "0006_alter_vote_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="comment",
        ),
        migrations.AlterField(
            model_name="vote",
            name="value",
            field=models.IntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
    ]
