# Generated by Django 4.2.6 on 2023-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subreddit", "0007_remove_vote_comment_alter_vote_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
