# Generated by Django 4.2.6 on 2023-10-12 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subreddit", "0010_post_disliked_by_post_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="disliked_by_comment",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_posts_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="liked_by_comment",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_posts_commment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
