# Generated by Django 4.2.6 on 2023-10-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0015_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subreddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subreddit.subreddit'),
        ),
    ]
