# Generated by Django 4.2.6 on 2023-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0016_message_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='subreddit.message'),
        ),
    ]
