# Generated by Django 4.2.4 on 2023-10-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0017_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subreddit_chat', to='subreddit.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='subreddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_subreddit', to='subreddit.subreddit'),
        ),
    ]
