# Generated by Django 4.2.6 on 2023-10-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0018_subreddit_chat_alter_chat_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
