# Generated by Django 4.2.6 on 2023-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0020_alter_reddituser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
