# Generated by Django 4.2.6 on 2023-10-19 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subreddit", "0021_alter_reddituser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="reddituser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
