# Generated by Django 4.1 on 2023-10-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0026_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
