# Generated by Django 4.1 on 2023-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0027_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], default='N', max_length=1),
        ),
    ]
