# Generated by Django 4.2.6 on 2023-10-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0028_reddituser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reddituser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users_interested', to='subreddit.interestcategory'),
        ),
    ]
