# Generated by Django 4.2.6 on 2023-10-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0030_alter_reddituser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='interests',
            field=models.ManyToManyField(blank=True, choices=[('AN', 'Anime'), ('CINE', 'Cinema'), ('DES', 'Desporto'), ('EDU', 'Educação'), ('IT', 'IT'), ('JOG', 'Jogos'), ('VIG', 'Viagens')], related_name='users_interested', to='subreddit.interestcategory'),
        ),
    ]
