# Generated by Django 4.2.6 on 2023-10-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0031_alter_reddituser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='interests',
            field=models.ManyToManyField(blank=True, choices=[('AN', '⛩ Anime'), ('CINE', '📽️ Cinema'), ('DES', '⚽ Desporto'), ('EDU', '📖 Educação'), ('IT', '🖥️ IT'), ('JOG', '🎮 Jogos'), ('VIG', '🗺️ Viagens')], to='subreddit.interestcategory'),
        ),
    ]
