# Generated by Django 4.2.6 on 2023-10-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0033_alter_reddituser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subreddit.interestcategory'),
        ),
    ]
